### ISSUE TITLE
Object popup

### ISSUE THREAD

**Issue by laba2346** [robertrenecker/boulderTrimble#12]
As a municipal worker, I want to click on object markers on the map so I can view more information about the objects.

GIVEN the user is on the map UI
AND object markers are displayed
WHEN the user clicks on the object marker
THEN a popup with more information about the object should appear

Design of said popup can be addressed later (alternatively, see the SRS)

**Comment by laba2346** [comment]
add information to the popups, similar to the mockups

**Comment by PlatPlat48** [comment]
I'll consider this done when it's been proven to work with Heroku.
