### ISSUE TITLE
Create two user stories for UI

### ISSUE THREAD

**Issue by laba2346** [robertrenecker/boulderTrimble#6]
This is so we can have requirements for the UI while Galen researches stuff

**Comment by robertrenecker** [comment]
As a municipal worker I want to know how many [important objects] are located in my neighborhood so I can compare that to other neighborhoods of the same size. 

As a municipal worker I want to know the most frequent important items that are located in a metropolitan area.

**Comment by PlatPlat48** [comment]
Make sure to put the user stories as actual issues in the backlog. Also make sure to follow the GIVEN/WHEN/THEN format.
